name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.93.82.254 >> ~/.ssh/known_hosts

      - name: Deploy to GCP VM
        run: |
          ssh -i ~/.ssh/id_rsa deepankarsinghvm@34.93.82.254 << 'EOF'
            cd ~/mern-project
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up --build -d
          EOF
